### ISSUE TITLE
I would like to join this organization

### ISSUE THREAD

**Issue by AvidCoder101** [devstrons/support#4]
@Panquesito7, I would like to join the devstrons organization please. Thanks (:

**Comment by Panquesito7** [comment]
I agree to add @AvidCoder101 to the organization. You should also join our [Discord server](https://discord.gg/SNNTC7ZKGz) and start looking out all the great things we got! @amino19, what do you think? 🙂

**Comment by amino19** [comment]
@AvidCoder101: Yes obviously, every contributor is welcome to the community! :slightly_smiling_face: 

But, we need to see your efforts towards the community in the way:  
- Active participation towards the organization.
- Step-in with a project's idea, & officially we'll host it in our organization.
- The project I mentioned above, will be maintained by **DEVSTRON**.
```
Q. What is DEVSTRON?
A. The member/folks of DEVSTRONS' Community, known as DEVSTRON.
```
Thanks for your patience reading!

But, we will soon automate this process! : )

**Comment by amino19** [comment]
So, @AvidCoder101 we automated this process successfully, feel free to join & would love to see your contribution; Welcoming you! :slightly_smiling_face:
