### ISSUE TITLE
i want to be maintener

### ISSUE THREAD

**Issue by ngdream** [devstrons/support#52]

**Comment by aminoxix** [comment]
Sure, there are few tendencies to work as a maintainer.

- You must be a member of DEVSTRONS' on every platform to be updated.
- You must contribute to one of the projects in @devstrons.
- You must have good knowledge & experience with Git & GitHub.
- You must first add a collaborator to any one of the projects and check how you're growing that!
- All admins will see your enthusiasm for the community.

&, I believe you'll be one of the maintainers at @devstrons, just focus & keep updated!
