### ISSUE TITLE
One of the CoC filenames must be `CODE_OF_CONDUCT.md`

### ISSUE THREAD

**Issue by Panquesito7** [devstrons/support#70]
### Description

There is two code of conduct files, but none of these are going to be detected by GitHub.
I tried searching if there was a way to have two codes of conduct, but I don't think that's possible.

We should rename one of the files to `CODE_OF_CONDUCT.md` so that GitHub detects it properly.
What do you think about this? And which one should we rename? 🤔

Thanks. 🙂

**Comment by aminoxix** [comment]
@Panquesito7 yes, would like to go ahead with this, what would you think to be the right COC for @devstrons?

**Comment by aminoxix** [comment]
- https://github.com/devstrons/support/commit/0b10a909887898be2b579b7113a7ab3879bf5afb
- https://github.com/devstrons/support/commit/04ff17fb2904d39cda0cc4a356db4090211c8601
